# Generated by Django 4.1.3 on 2022-12-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.IntegerField(unique=True, verbose_name='Заявка на покупку')),
                ('application_date', models.DateTimeField(verbose_name='Дата подачи заявки')),
                ('application_validity_period', models.DateTimeField(verbose_name='Срок действия заявки')),
                ('procurement_name', models.TextField(verbose_name='Наименование покупки')),
                ('product_information', models.TextField(null=True, verbose_name='Информация о товаре')),
                ('brand', models.CharField(max_length=255, null=True, verbose_name='Бренд')),
                ('producing_country', models.CharField(max_length=150, null=True, verbose_name='Страна-производитель')),
                ('buyer_country', models.CharField(max_length=150, null=True, verbose_name='Страна-покупатель')),
                ('qntunits', models.CharField(max_length=30, null=True, verbose_name='Единицы измерения товара')),
                ('terms_of_payment', models.TextField(null=True, verbose_name='Условия оплаты')),
                ('delivery_conditions', models.TextField(null=True, verbose_name='Условия поставки')),
                ('delivery_time', models.CharField(max_length=100, null=True, verbose_name='Время доставки')),
                ('exposure_time', models.DateTimeField(verbose_name='Время экспозиции')),
                ('application_is_bidding', models.CharField(max_length=255, verbose_name='Заявка участвует в торгах')),
                ('price', models.FloatField(verbose_name='Цена (без НДС)')),
                ('number_of_goods', models.IntegerField(verbose_name='Количество товара')),
                ('cost', models.FloatField(verbose_name='Стоимость (без НДС)')),
                ('currency', models.CharField(max_length=50, verbose_name='Валюта')),
                ('technical_documentation_file_name', models.CharField(max_length=100, null=True, verbose_name='Файл технической документации')),
                ('application_link', models.URLField(verbose_name='Ссылка на заявку')),
                ('scraping_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего парсинга')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
    ]
