# Generated by Django 4.1.3 on 2022-12-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='slug',
            field=models.SlugField(verbose_name='URL'),
        ),
    ]
