# Generated by Django 4.1.3 on 2022-12-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0002_alter_bid_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL'),
        ),
    ]
