# Generated by Django 4.1.3 on 2022-12-10 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bid', '0003_alter_bid_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='bid',
            name='manager_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='number_of_subcount',
            field=models.IntegerField(null=True, verbose_name='Количество заявок на покупку'),
        ),
        migrations.AddField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Активные'), ('INACTIVE', 'Неактивные')], default='ACTIVE', max_length=30),
        ),
        migrations.AddField(
            model_name='bid',
            name='subcount_link',
            field=models.URLField(null=True, verbose_name='Заявки на покупку'),
        ),
        migrations.AddField(
            model_name='bid',
            name='tnvedcode',
            field=models.IntegerField(null=True, verbose_name='Код'),
        ),
    ]
