# Generated by Django 4.1.3 on 2022-12-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bid', '0004_bid_comment_bid_manager_id_bid_number_of_subcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='tnvedcode',
            field=models.BigIntegerField(null=True, verbose_name='Код'),
        ),
    ]
