# Generated by Django 4.1.3 on 2022-12-24 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='auth-token')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField()),
                ('message', models.TextField(verbose_name='message')),
                ('is_read', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True)),
                ('product_name', models.TextField()),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=10)),
                ('full_cost', models.BigIntegerField()),
                ('qntunits', models.CharField(max_length=10)),
                ('quantity', models.FloatField()),
                ('validity', models.DateTimeField()),
                ('trade_category', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255, null=True)),
                ('status_in_trade', models.CharField(default=None, max_length=255)),
                ('status', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.IntegerField(unique=True)),
                ('application_date', models.DateTimeField(null=True)),
                ('application_validity_period', models.DateTimeField(null=True)),
                ('procurement_name', models.TextField(null=True)),
                ('product_information', models.TextField(null=True)),
                ('brand', models.CharField(max_length=255, null=True)),
                ('producing_country', models.CharField(max_length=150, null=True)),
                ('buyer_country', models.CharField(max_length=150, null=True)),
                ('qntunits', models.CharField(max_length=30, null=True)),
                ('terms_of_payment', models.TextField(null=True)),
                ('delivery_conditions', models.TextField(null=True)),
                ('delivery_time', models.CharField(max_length=100, null=True)),
                ('exposure_time', models.DateTimeField(null=True)),
                ('application_is_bidding', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('number_of_goods', models.IntegerField()),
                ('cost', models.FloatField()),
                ('currency', models.CharField(max_length=50)),
                ('technical_documentation_file_name', models.CharField(max_length=100, null=True)),
                ('application_link', models.URLField(null=True)),
                ('scraping_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('comment', models.TextField(blank=True, default=None, null=True)),
                ('tnvedcode', models.BigIntegerField(null=True)),
                ('number_of_subcount', models.IntegerField(null=True)),
                ('subcount_link', models.URLField(null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=30)),
                ('trade_status', models.CharField(choices=[(1, 'send_offers'), (2, 'close period'), (3, 'lead_offer'), (4, 'result trades')], default=None, max_length=100, null=True)),
                ('trade_status_message', models.CharField(default=None, max_length=255, null=True)),
                ('activityStatus', models.IntegerField(default=0, null=True)),
                ('offer', models.ManyToManyField(to='api.offer')),
            ],
        ),
    ]
