# Generated by Django 4.1.3 on 2022-12-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='auth-token')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('number', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='▒~]оме▒~@ за▒~Oвки на п▒~@одаж▒~C')),
                ('product_name', models.TextField(verbose_name='▒~]аименование')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('currency', models.CharField(max_length=10, verbose_name='▒~Rал▒~N▒~Bа')),
                ('full_cost', models.BigIntegerField(verbose_name='▒~_олна▒~O ▒~Fена')),
                ('qntunits', models.CharField(max_length=10, verbose_name='▒~Uдини▒~Fа изме▒~@ени▒~O')),
                ('quantity', models.FloatField(verbose_name='▒~Zоли▒~Gе▒~A▒~Bво')),
                ('validity', models.DateTimeField(verbose_name='С▒~@ок дей▒~A▒~Bви▒~O за▒~Oвки')),
                ('trade_category', models.CharField(max_length=255, verbose_name='▒~Zа▒~Bего▒~@и▒~O ▒~Bо▒~@гов')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='С▒~B▒~@ана')),
                ('status_in_trade', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_order', models.IntegerField(unique=True)),
                ('application_date', models.DateTimeField(null=True, verbose_name='▒~Tа▒~Bа пода▒~Gи за▒~Oвки')),
                ('application_validity_period', models.DateTimeField(null=True, verbose_name='С▒~@ок дей▒~A▒~Bви▒~O за▒~Oвки')),
                ('procurement_name', models.TextField(null=True, verbose_name='▒~]аименование пок▒~Cпки')),
                ('product_information', models.TextField(null=True, verbose_name='▒~Xн▒~Dо▒~@ма▒~Fи▒~O о ▒~Bова▒~@е')),
                ('brand', models.CharField(max_length=255, null=True, verbose_name='▒~Q▒~@енд')),
                ('producing_country', models.CharField(max_length=150, null=True, verbose_name='С▒~B▒~@ана-п▒~@оизводи▒~Bел▒~L')),
                ('buyer_country', models.CharField(max_length=150, null=True, verbose_name='С▒~B▒~@ана-пок▒~Cпа▒~Bел▒~L')),
                ('qntunits', models.CharField(max_length=30, null=True, verbose_name='▒~Uдини▒~F▒~K изме▒~@ени▒~O ▒~Bова▒~@а')),
                ('terms_of_payment', models.TextField(null=True, verbose_name='У▒~Aлови▒~O опла▒~B▒~K')),
                ('delivery_conditions', models.TextField(null=True, verbose_name='У▒~Aлови▒~O по▒~A▒~Bавки')),
                ('delivery_time', models.CharField(max_length=100, null=True, verbose_name='▒~R▒~@ем▒~O до▒~A▒~Bавки')),
                ('exposure_time', models.DateTimeField(null=True, verbose_name='▒~R▒~@ем▒~O ▒~Mк▒~Aпози▒~Fии')),
                ('application_is_bidding', models.CharField(max_length=255, verbose_name='▒~Wа▒~Oвка ▒~C▒~Gа▒~A▒~Bв▒~Cе▒~B в ▒~Bо▒~@га▒~E')),
                ('price', models.FloatField(verbose_name='Цена (без ▒~]▒~TС)')),
                ('number_of_goods', models.IntegerField(verbose_name='▒~Zоли▒~Gе▒~A▒~Bво ▒~Bова▒~@а')),
                ('cost', models.FloatField(verbose_name='С▒~Bоимо▒~A▒~B▒~L (без ▒~]▒~TС)')),
                ('currency', models.CharField(max_length=50, verbose_name='▒~Rал▒~N▒~Bа')),
                ('technical_documentation_file_name', models.CharField(max_length=100, null=True, verbose_name='Файл ▒~Bе▒~Eни▒~Gе▒~Aкой док▒~Cмен▒~Bа▒~Fии')),
                ('application_link', models.URLField(null=True, verbose_name='С▒~A▒~Kлка на за▒~Oвк▒~C')),
                ('scraping_date', models.DateTimeField(auto_now_add=True, verbose_name='▒~Tа▒~Bа по▒~Aледнего па▒~@▒~Aинга')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='▒~Zоммен▒~Bа▒~@ий')),
                ('tnvedcode', models.BigIntegerField(null=True, verbose_name='▒~Zод')),
                ('number_of_subcount', models.IntegerField(null=True, verbose_name='▒~Zоли▒~Gе▒~A▒~Bво за▒~Oвок на пок▒~Cпк▒~C')),
                ('subcount_link', models.URLField(null=True, verbose_name='▒~Wа▒~Oвки на пок▒~Cпк▒~C')),
                ('status', models.CharField(choices=[('ACTIVE', '▒~Pк▒~Bивн▒~Kе'), ('INACTIVE', '▒~]еак▒~Bивн▒~Kе')], default='ACTIVE', max_length=30)),
                ('trade_status', models.CharField(choices=[(1, '▒~]ап▒~@авление п▒~@едложений'), (2, '▒~Wак▒~@▒~K▒~B▒~Kй пе▒~@иод'), (4, '▒~X▒~Bоги ▒~Bо▒~@гов')], default=None, max_length=100, null=True, verbose_name='С▒~Bа▒~B▒~C▒~A ▒~Bо▒~@гов')),
                ('trade_status_message', models.CharField(default=None, max_length=255, null=True)),
                ('activityStatus', models.IntegerField(default=0, null=True)),
                ('offer', models.ManyToManyField(to='api.offer')),
            ],
        ),
    ]
