# Generated by Django 4.1.3 on 2022-12-21 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField()),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
        migrations.AlterField(
            model_name='bid',
            name='application_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='application_is_bidding',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='bid',
            name='application_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='application_validity_period',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='brand',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='buyer_country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='comment',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bid',
            name='delivery_conditions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='delivery_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='exposure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_of_goods',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='number_of_subcount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='procurement_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='producing_country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='product_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='qntunits',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='scraping_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('INACTIVE', 'inactive')], default='ACTIVE', max_length=30),
        ),
        migrations.AlterField(
            model_name='bid',
            name='subcount_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='technical_documentation_file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='terms_of_payment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='tnvedcode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='trade_status',
            field=models.CharField(choices=[(1, 'send_offers'), (2, 'close period'), (3, 'lead_offer'), (4, 'result trades')], default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='full_cost',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='number',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='product_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='qntunits',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='trade_category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='validity',
            field=models.DateTimeField(),
        ),
    ]
