# Generated by Django 4.1.3 on 2022-12-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='statusOrderNotification',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='statusOrders',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
