# Generated by Django 4.1.3 on 2022-12-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_notification_alter_bid_application_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
