# Generated by Django 4.1.3 on 2022-12-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_offer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status_in_trade',
            field=models.CharField(default=None, max_length=255, null=True, verbose_name='Статус в торгах'),
        ),
    ]
