# Generated by Django 4.1.3 on 2022-12-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_offer_bid_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='bid_id',
        ),
    ]
