# Generated by Django 4.1.3 on 2022-12-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
