# Generated by Django 4.1.3 on 2022-12-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_offer_status_in_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='application_date',
            field=models.DateTimeField(null=True, verbose_name='Дата подачи заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='application_link',
            field=models.URLField(null=True, verbose_name='Ссылка на заявку'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='application_validity_period',
            field=models.DateTimeField(null=True, verbose_name='Срок действия заявки'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='exposure_time',
            field=models.DateTimeField(null=True, verbose_name='Время экспозиции'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='procurement_name',
            field=models.TextField(null=True, verbose_name='Наименование покупки'),
        ),
    ]
