# Generated by Django 4.1.3 on 2022-12-13 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_offer_bid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arhive',
            fields=[
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bid_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.bid')),
            ],
        ),
    ]
