# Generated by Django 4.1.3 on 2022-12-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_bid_statusordernotification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='number',
        ),
        migrations.AlterField(
            model_name='bid',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
