# Generated by Django 4.1.3 on 2022-12-13 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_arhive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='auth-token')),
            ],
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='bid_id',
            new_name='bid',
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(verbose_name='Номер сделки')),
                ('Offer', models.ManyToManyField(to='api.offer')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bid')),
            ],
        ),
    ]
