# Generated by Django 4.1.3 on 2022-12-13 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auth_token_rename_manager_id_bid_manager_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
