# Generated by Django 4.1.3 on 2022-12-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_bid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='statusOrders',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
