# Generated by Django 4.1.3 on 2022-12-13 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_trades_trade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arhive',
            old_name='bid_id',
            new_name='bid',
        ),
        migrations.AddField(
            model_name='offer',
            name='status_in_trade',
            field=models.CharField(default=None, max_length=255, verbose_name='Статус в торгах'),
        ),
        migrations.AddField(
            model_name='trade',
            name='User',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='country',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='trade',
            name='currency',
            field=models.CharField(default=None, max_length=10, verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='full_cost',
            field=models.BigIntegerField(default=None, verbose_name='Полная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='price',
            field=models.FloatField(default=None, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='productname',
            field=models.CharField(default=None, max_length=255, verbose_name='Наименование продукта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='qntunits',
            field=models.CharField(default=None, max_length=10, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.FloatField(default=None, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_category',
            field=models.CharField(default=None, max_length=255, verbose_name='Категория торгов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(choices=[('OPEN_TO_OFFERS', 'Направление предложений'), ('CLOSE PERIOD', 'Закрытый период'), ('TRADING RESULTS', 'Итоги торгов')], default=None, max_length=50, verbose_name='Статус сделки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='validity',
            field=models.DateTimeField(default=None, verbose_name='Срок действия заявки'),
            preserve_default=False,
        ),
    ]
