# Generated by Django 4.1.3 on 2022-12-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bid_statusorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='statusOrderNotification',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
