# Generated by Django 4.1.3 on 2022-12-13 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_bid_id_arhive_bid_offer_status_in_trade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='manager',
            new_name='trader',
        ),
        migrations.AddField(
            model_name='bid',
            name='trade_status',
            field=models.CharField(choices=[(1, 'Направление предложений'), (2, 'Закрытый период'), (4, 'Итоги торгов')], default=None, max_length=100, null=True, verbose_name='Статус торгов'),
        ),
        migrations.AddField(
            model_name='bid',
            name='trade_status_message',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='trader',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
    ]
