# Generated by Django 4.1.3 on 2022-12-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_manager_bid_trader_bid_trade_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Arhive',
        ),
    ]
