# Generated by Django 4.1.3 on 2022-12-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_bid_statusorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
